--INDICE OCORRENCIA
CREATE INDEX IDX_OCORRENCIA ON MED_OCORRENCIA(CD_OCORRENCIA, NM_NOME, CD_SITUACAO, FL_TIPO_OCORRENCIA);

--INDICE GRUPO FATURAMENTO
CREATE INDEX IDX_GRUPOFATURAMENTO ON MED_GRUPO_FATURAMENTO(CD_GRUPO_FATURAMENTO, CD_SITUACAO);

--INDICE DISTRIBUICAO LEITURA REGISTRO
CREATE INDEX IDX_DISTRIBUICAOLEITURA ON MED_DISTRIBUICAO_LEITURA_REGISTRO(ID_REGIONAL, ID_LEITURA, ID_USUARIO, FL_ASSOCIADO);

--INDICE IMPORTACAO
CREATE INDEX IDX_IMPORTACAO ON MED_IMPORTACAO(ID_REGIONAL, ID_GRUPO_FATURAMENTO, ID_USUARIO, DT_ANO_MES_REF);

--INDICE EXPORTACAO
CREATE INDEX IDX_EXPORTACAO ON MED_EXPORTACAO(ID_REGIONAL, ID_GRUPO_FATURAMENTO, ID_USUARIO, DT_ANO_MES_REF);

--INDICE LEITURA
CREATE INDEX IDX_LEITURA ON MED_LEITURA(ID_IMPORTACAO, ID_GRUPO_FATURAMENTO, CD_TAREFA_LEITURA, CD_TAREFA_ENTREGA, NR_INSTALACAO, NR_MEDIDOR, CD_OCORRENCIA);

--INDICE RETORNO FOTO
CREATE INDEX IDX_RETORNOFOTO ON RETORNO_FOTO(ID_LEITURA, ID_USUARIO, NM_NOME, DS_PATH, NR_INSTALACAO, NR_MEDIDOR);

--INDICE RETORNO LEITURA
CREATE INDEX IDX_RETORNOLEITURA ON MED_RETORNO_LEITURA(ID_LEITURA, ID_REGIONAL, ID_USUARIO, ID_OCORRENCIA, ID_GRUPO_FATURAMENTO, DT_ANO_MES_REF, NR_INSTALACAO, NR_MEDIDOR, FL_FOTO, FL_ATIVO, CD_LATITUDE, CD_LONGITUDE);

--INDICE USUARIO REGIONAL
CREATE INDEX IDX_USUARIOREGIONAL ON SEG_USUARIO_REGIONAL(ID_REGIONAL, ID_USUARIO);

--INDICE USUARIO
CREATE INDEX IDX_USUARIO ON SEG_USUARIO(ID_PERFIL_ACESSO, NR_MATRICULA);
